# Generated by Django 4.0.3 on 2022-03-10 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_comment_post_delete_article_delete_journalist_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author_date',
            new_name='author_name',
        ),
    ]
